##############################################################
#                                                            #
# Xeon(R) + FPGA AFU Simulation Environment                  #
# File generated by ase/scripts/generate_ase_environment.py  #
#                                                            #
##############################################################

DUT_VLOG_SRC_LIST = $(ASE_SRCDIR)/vlog_files.list 

DUT_INCDIR = $(ASEVAL_GIT)/test_afus/ccip_dcp_hello_mem/HW/+$(ASEVAL_GIT)/test_afus/ccip_dcp_hello_mem/HW/+

SIMULATOR ?= VCS

ASE_PLATFORM ?= FPGA_PLATFORM_DISCRETE

