####################################################################
#                                                                  #
# Xeon(R) + FPGA AFU Simulation Environment                        #
# File generated by AALSDK/ase/scripts/generate_ase_environment.py #
#                                                                  #
####################################################################

DUT_VLOG_SRC_LIST = $(ASE_SRCDIR)/vlog_files.list 

DUT_INCDIR = $(AALSDK_GIT)/valapps/MMIO_Mapping/RTL_valid_DFH/+

ASEHW_FILE_LIST = \
	$(ASE_SRCDIR)/hw/ccip_if_pkg.sv \
	$(ASE_SRCDIR)/hw/ase_pkg.sv \
	$(ASE_SRCDIR)/hw/outoforder_wrf_channel.sv \
	$(ASE_SRCDIR)/hw/latency_pipe.sv \
	$(ASE_SRCDIR)/hw/ccip_emulator.sv \
	$(ASE_SRCDIR)/hw/ase_svfifo.sv \
	$(ASE_SRCDIR)/hw/ccip_logger.sv \
	$(ASE_SRCDIR)/hw/ccip_sniffer.sv \
	$(ASE_SRCDIR)/hw/ase_top.sv \


ASE_INCDIR = $(ASE_SRCDIR)/hw/+

ASESW_FILE_LIST = \
	$(ASE_SRCDIR)/sw/ase_ops.c \
	$(ASE_SRCDIR)/sw/ipc_mgmt_ops.c \
	$(ASE_SRCDIR)/sw/mem_model.c \
	$(ASE_SRCDIR)/sw/protocol_backend.c \
	$(ASE_SRCDIR)/sw/tstamp_ops.c \
	$(ASE_SRCDIR)/sw/mqueue_ops.c \
	$(ASE_SRCDIR)/sw/error_report.c \
	$(ASE_SRCDIR)/sw/linked_list_ops.c \
	$(ASE_SRCDIR)/sw/randomness_control.c \


ASE_TOP = ase_top

SIMULATOR ?= VCS

