####################################################################
#                                                                  #
# Xeon(R) + FPGA AFU Simulation Environment                        #
# File generated by AALSDK/ase/scripts/generate_ase_environment.py #
#                                                                  #
####################################################################

DUT_VLOG_SRC_LIST = /home/diptishe/JENKINS_test/cpt_sys_sw-fpga-sw/ase/vlog_files.list 

DUT_INCDIR = /home/diptishe/JENKINS_test/atd_fpga_app-qa_bblocks/BBB_cci_mpf/test/test-mpf/test_random/hw/rtl/+/home/diptishe/JENKINS_test/atd_fpga_app-qa_bblocks/BBB_cci_mpf/hw/rtl/+/home/diptishe/JENKINS_test/atd_fpga_app-qa_bblocks/BBB_cci_mpf/hw/rtl/cci-if+/home/diptishe/JENKINS_test/atd_fpga_app-qa_bblocks/BBB_cci_mpf/hw/rtl/cci-mpf-shims+/home/diptishe/JENKINS_test/atd_fpga_app-qa_bblocks/BBB_cci_mpf/hw/rtl/cci-mpf-shims/cci_mpf_shim_wro+/home/diptishe/JENKINS_test/atd_fpga_app-qa_bblocks/BBB_cci_mpf/hw/rtl/cci-mpf-shims/cci_mpf_shim_pwrite+/home/diptishe/JENKINS_test/atd_fpga_app-qa_bblocks/BBB_cci_mpf/hw/rtl/cci-mpf-shims/cci_mpf_shim_edge+/home/diptishe/JENKINS_test/atd_fpga_app-qa_bblocks/BBB_cci_mpf/hw/rtl/cci-mpf-shims/cci_mpf_shim_vtp+/home/diptishe/JENKINS_test/atd_fpga_app-qa_bblocks/BBB_cci_mpf/hw/rtl/cci-mpf-if+/home/diptishe/JENKINS_test/atd_fpga_app-qa_bblocks/BBB_cci_mpf/hw/rtl/cci-mpf-prims+/home/diptishe/JENKINS_test/atd_fpga_app-qa_bblocks/BBB_cci_mpf/test/test-mpf/base/hw/rtl/+

ASE_TOP = ase_top

SIMULATOR ?= VCS

