####################################################################
#                                                                  #
# Xeon(R) + FPGA AFU Simulation Environment                        #
# File generated by AALSDK/ase/scripts/generate_ase_environment.py #
#                                                                  #
####################################################################

DUT_VLOG_SRC_LIST = $(ASE_SRCDIR)/vlog_files.list 

DUT_INCDIR = $(BBB_GIT)/BBB_cci_mpf/test/test-mpf/test_random/hw/rtl/+$(BBB_cci_mpf)/BBB_cci_mpf/hw/rtl/+$(BBB_GIT)/BBB_cci_mpf/hw/rtl/cci-if+$(BBB_GIT)/BBB_cci_mpf/hw/rtl/cci-mpf-shims+$(BBB_GIT)/BBB_cci_mpf/hw/rtl/cci-mpf-shims/cci_mpf_shim_wro+$(BBB_GIT)/BBB_cci_mpf/hw/rtl/cci-mpf-shims/cci_mpf_shim_pwrite+$(BBB_GIT)/BBB_cci_mpf/hw/rtl/cci-mpf-shims/cci_mpf_shim_edge+$(BBB_GIT)/BBB_cci_mpf/hw/rtl/cci-mpf-shims/cci_mpf_shim_vtp+$(BBB_GIT)/BBB_cci_mpf/hw/rtl/cci-mpf-if+$(BBB_GIT)/BBB_cci_mpf/hw/rtl/cci-mpf-prims+$(BBB_GIT)/BBB_cci_mpf/test/test-mpf/base/hw/rtl/+

ASE_TOP = ase_top

SIMULATOR ?= VCS

