####################################################################
#                                                                  #
# Xeon(R) + FPGA AFU Simulation Environment                        #
# File generated by AALSDK/ase/scripts/generate_ase_environment.py #
#                                                                  #
####################################################################

DUT_VLOG_SRC_LIST = vlog_files.list 

DUT_INCDIR = $(ASEVAL_GIT)/test_afus/ccip_simple/HW/+

ASE_TOP = ase_top

SIMULATOR ?= VCS

